<a href="https://colab.research.google.com/github/Rifana22/Learn.py/blob/main/TASK_14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create two arrays, one containing elements [1,2], [3,4] and another containing elements [8,18] Now find the solution for this linear equation.

In [2]:
#please type your answer below this line.
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[8],[18]])
print(a)
print(b)
Sol=np.linalg.solve(a,b)
print(Sol)

[[1 2]
 [3 4]]
[[ 8]
 [18]]
[[2.]
 [3.]]


2. Create an array containing elements [2, 3, 4]. Now find the sin,cos,tan values of this array elements.

In [3]:
#please type your answer below this line.
import numpy as np
a=np.array([2,3,4])
print(a)
sin=np.sin(a)
print(sin)
cos=np.cos(a)
print(cos)
tan=np.tan(a)
print(tan)

[2 3 4]
[ 0.90929743  0.14112001 -0.7568025 ]
[-0.41614684 -0.9899925  -0.65364362]
[-2.18503986 -0.14254654  1.15782128]


3. Given b=[5,6], then find,

  a) 2sinb
  b) 2cos3b
  c) 4tan2b

In [4]:
#please type your answer below this line.
import numpy as np
b=np.array([5,6])
print(b)
a=2*np.sin(b)
print(a)
b2=2*np.cos(3*b)
print(b2)
c=4*np.tan(2*b)
print(c)

[5 6]
[-1.91784855 -0.558831  ]
[-1.51937583  1.32063342]
[ 2.59344331 -2.54343971]
