<a href="https://colab.research.google.com/github/Rifana22/Learn.py/blob/main/TASK_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [7]:
#please provide your answer below this line.
import numpy as np
array = np.random.randint(10,size=(3,3))
print(array)

[[2 7 9]
 [5 6 7]
 [1 0 3]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [8]:
#please provide your answer below this line.
 
import numpy as np
array1= np.random.randint(10,size=(4,4))
print(array1)
array2=np.random.randint(10,size=(4,4))
print(array2)
x=array1.reshape(2,8)
y=array2.reshape(2,8)
print (np.hstack((x,y)))
print (np.vstack((x,y)))

[[0 4 9 0]
 [6 8 5 1]
 [8 6 8 4]
 [6 2 8 3]]
[[2 2 5 1]
 [5 8 4 6]
 [4 0 1 6]
 [7 5 3 8]]
[[0 4 9 0 6 8 5 1 2 2 5 1 5 8 4 6]
 [8 6 8 4 6 2 8 3 4 0 1 6 7 5 3 8]]
[[0 4 9 0 6 8 5 1]
 [8 6 8 4 6 2 8 3]
 [2 2 5 1 5 8 4 6]
 [4 0 1 6 7 5 3 8]]
