<a href="https://colab.research.google.com/github/Rifana22/Learn.py/blob/main/TASK_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate two  3 x 3 matrix and find it's dot product and take the transpose of the answer.

In [2]:
#please provide your answer below this line.
import numpy as np
x=np.arange(1,10).reshape(3,3)
y=np.arange(11,20).reshape(3,3)
print(x)
print(y)
c=np.dot(x,y)
print(c)
print(np.transpose(c))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 90  96 102]
 [216 231 246]
 [342 366 390]]
[[ 90 216 342]
 [ 96 231 366]
 [102 246 390]]


2. Create a 3x3 matrix with elements [55,25,15], [30,44,2], [11,45,77] . Now find the determinant of the given matrix.

In [4]:
#please provide your answer below this line.
import numpy as np
x=np.array([[55,25,15],[30,44,2],[11,45,77]])
print(x)
d=np.linalg.det(x)
print(d)

[[55 25 15]
 [30 44  2]
 [11 45 77]]
137180.0000000001
